### ISSUE TITLE
Syntax error in add-site.sh

### ISSUE THREAD

**Issue by nternetinspired** [betweenbrain/ubuntu-web-server-build-script#12]
Running the script, in a clean install using build.sh, gives this error:
## Creating VirtualHost for mysite.com

./add-site.sh: line 84: syntax error near unexpected token `('
./add-site.sh: line 84:`           <FilesMatch "\.(cgi|shtml|phtml|php)$">'

Of course I checked against etc/apache2/sites-available/default-ssl and found no differences in the syntax. 

I removed the parentheses to give:

<FilesMatch "\.cgi|shtml|phtml|php$">'

The script then ran to completion with no errors but results in both /etc/apache2/sites-available and /sites-enabled containing 0 byte files for the domain

**Comment by betweenbrain** [comment]
Hi Seth,

Thanks! I think the syntax for that line should be `<FilesMatch \"\.(cgi|shtml|phtml|php)$\">` instead of `<FilesMatch \"\\.(cgi|shtml|phtml|php)$\">` It looks like I had one too many backslashes before the dot. Will test now.

**Comment by nternetinspired** [comment]
You were missing a set of \ , you proposed revision fixes it for me. 

Thanks.

**Comment by betweenbrain** [comment]
Thanks! Looks like add-site.sh was out of sync with build.sh as well.
